export type DataStateCategory = 'MECHANISTIC' | 'AI PREDICTION' | 'HISTORICAL';

export interface DataStateBadgeConfig {
  label: DataStateCategory;
  bgColor: string;
  textColor: string;
  borderColor: string;
  description: string;
}

export const DATA_STATE_BADGES: Record<DataStateCategory, DataStateBadgeConfig> = {
  MECHANISTIC: {
    label: 'MECHANISTIC',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    description: 'Generated by CHO cell perfusion mechanistic ODE engine'
  },
  'AI PREDICTION': {
    label: 'AI PREDICTION',
    bgColor: 'bg-emerald-50',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    description: 'Data-driven bioprocess outcome prediction (Dataset 2 HistGradientBoosting)'
  },
  HISTORICAL: {
    label: 'HISTORICAL',
    bgColor: 'bg-amber-50',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    description: 'Observed empirical evidence from published biomanufacturing literature'
  }
};

export interface TiterInputParams {
  temperature: number;
  substrate_concentration: number;
  reactor_volume: number;
  oxygen: number;
  fermentation_duration: number;
}

export interface TiterPredictionResponse {
  prediction: number;
  unit: string;
  target: string;
  target_transform: string;
  model: string;
  version: string;
  dataset: string;
  dataset_observations: number;
  dataset_papers: number;
  domain_status: 'IN_DOMAIN' | 'EXTRAPOLATIVE';
  domain_notes?: string | null;
  validated_model_domain?: Record<string, DomainBound>;
  observed_training_range?: Record<string, DomainBound>;
}

export interface SimilarityQueryParams {
  temperature: number;
  substrate_concentration: number;
  reactor_volume: number;
  oxygen: number;
  fermentation_duration: number;
}

export interface SimilarityMatchItem {
  rank: number;
  paper_id: string;
  product_name: string;
  strain_background: string;
  observed_titer: number;
  temperature?: number | null;
  substrate_concentration?: number | null;
  reactor_volume?: number | null;
  oxygen?: number | null;
  fermentation_duration?: number | null;
  distance: number;
  is_self_match: boolean;
}

export interface SimilarityResponse {
  query: Record<string, number>;
  matches_count: number;
  domain_status: 'IN_DOMAIN' | 'OUT_OF_DOMAIN';
  matches: SimilarityMatchItem[];
}

export interface DomainBound {
  min: number;
  max: number;
}

export interface TiterModelInfo {
  model_id: string;
  model_version: string;
  dataset: string;
  dataset_source: string;
  process_type: string;
  target: string;
  target_unit: string;
  target_transform: string;
  algorithm: string;
  feature_set: string;
  features: string[];
  domain_bounds: Record<string, DomainBound>;
  observed_training_range?: Record<string, DomainBound>;
  dataset_observations: number;
  dataset_papers: number;
  training_rows: number;
  validation_rows: number;
  test_rows: number;
  training_papers_count: number;
  validation_papers_count: number;
  test_papers_count: number;
  training_timestamp: string;
  validation_metrics: {
    r2: number;
    mae: number;
    rmse: number;
    medae: number;
  };
  test_metrics: {
    r2: number;
    mae: number;
    rmse: number;
    medae: number;
  };
}

export interface TiterModelPerformance {
  model_id: string;
  model_version: string;
  target: string;
  target_unit: string;
  target_transform: string;
  algorithm: string;
  dataset_observations: number;
  dataset_papers: number;
  validation_metrics: {
    r2: number;
    mae: number;
    rmse: number;
    medae: number;
  };
  test_metrics: {
    r2: number;
    mae: number;
    rmse: number;
    medae: number;
  };
}

export interface AIAnalysisHistoryItem {
  id: string;
  simulationTime: number;
  timestamp: string;
  source: 'TWIN' | 'MANUAL' | 'MIXED';
  inputs: TiterInputParams;
  inputSources: Record<string, 'TWIN' | 'MANUAL'>;
  prediction: TiterPredictionResponse;
  similarityMatches: SimilarityResponse | null;
}

export interface AIServiceState {
  available: boolean;
  loading: boolean;
  error: string | null;
  modelInfo: TiterModelInfo | null;
  modelPerformance: TiterModelPerformance | null;
  currentPrediction: TiterPredictionResponse | null;
  similarityMatches: SimilarityResponse | null;
  isPredicting: boolean;
  isSearchingSimilarity: boolean;
  analysisHistory: AIAnalysisHistoryItem[];
}
